Us03 login
P-Name-Undefined/Frontend pull request #10
Opened 2020-04-15 18:58 UTC by MatheusEstanislau

## Descrição 

Criado Telas de Login, formulário de cadastro, foto do usuário, grupo de risco e localização do usuário
## Resolve (Issues)
- [US03 - Logar (Email/Senha)](https://github.com/mia-ajuda/Documentation/issues/5)
- [US05 - Cadastrar (Email/Senha)](https://github.com/mia-ajuda/Documentation/issues/7)
- [US09 - Informar (Grupo de risco)](https://github.com/mia-ajuda/Documentation/issues/11)
- [US11 - Adicionar foto ](https://github.com/mia-ajuda/Documentation/issues/13)
- [US12 - Compartilhar localização](https://github.com/mia-ajuda/Documentation/issues/14)

## Tarefas gerais realizadas
* Login
* Cadastro

## Passos necessários para testar

- Rodar os dois ambientes já configurados com os arquivos do Firebase que etão no drive do projeto
- Entrar na plataforma do Firebase logado com a conta do projeto
- Evitar números de telefone e cpf que já estejam no firebase
- É necessário utilizar um gerador de CPF real por causa da validação

2020-04-15 20:19 UTC, LhTaira requested changes

2020-04-15 20:19 UTC, LhTaira commented on app/src/pages/authPages/RegistrationData/index.js
> +            label="Senha (mais de 8 caracteres)"
Trocar para "Pelo menos 8 caracteres" pois "mais de 8" implicaria um minimo de 9 caracteres.

2020-04-16 18:31 UTC, GabrielDVpereira requested changes

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/pages/authPages/Location/index.js
> +      location: {
O back espera uma latitude e longitude como parametros do objeto e não dentro de um atributo location

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/routes.js
> +    {/* <AuthStack.Navigator initialRouteName="login" screenOptions={headerStyle}>
Remover código comentado, sugiro usar o AuthStack para o nome da navegação em pilha do login ao invés de StackNavigation que é um nome mais genérico.

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/services/User.js
> +      const idTokenUser = await firebaseAuth
A chamada do serviço firebaseAuth.auth().signInWithEmailAndPassword retorna em seu corpo stsTokenManager.accessToken que possui o mesmo valor que será armazenado pelo idTokenUser, fazendo desnecessária a chamada da função getIdToken. Retirando esse valor haverá melhora na performace do login

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/components/UI/selectBox/index.js
> +  select=false
Não consegui reconhecer essas mudanças, na pagina de selectBox sendo aplicada em outra parte do projeto. Da forma como está esse arquivo atualmete não está fazendo com que o checkbox se comporte como esperado

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/config/envVariables.js
> +// const devUrl = `http://192.168.15.10:8000/api`;
retirar comentário

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/components/UI/selectBox/styles.js
> +  container: {
Esse estilo gerou uma má formatação do selectBox no modal de filtro de categoria, onde está sendo usado o selectBox além da pagina de filtro?

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/pages/authPages/PersonalData/index.js
> +import CheckBox from "../../../components/UI/selectBox";
Usar import { CheckBox } from "react-native-elements";

2020-04-16 18:31 UTC, GabrielDVpereira commented on app/src/pages/authPages/PersonalData/index.js
> +              category={{}}
Retirar filterCategoryArray, category, setSelectedCategoryArray e usar o método onPress ao invés de onChange

2020-04-16 20:48 UTC, merged

2021-10-02 18:22 UTC, 4devs-net-br commented
https://4devs.net.br/gerador-cpf