M19 - [FAQ] Tela de Ajuda do Aplicativo
P-Name-Undefined/Frontend pull request #109
Opened 2020-08-12 02:15 UTC by devsalula

## Descrição 

Foi construído uma tela com a explicação das funcionalidades básicas da aplicação. Exemplo: Como utilizar o Mia Ajuda? Como criar uma oferta de ajuda? etc.

## Resolve (Issues)

[M19](https://github.com/mia-ajuda/Documentation/issues/158)

## Tarefas gerais realizadas
* Criado a tela de FAQ;
* Criado Botões na tela de FAQ, que direcionam pra Modais com informações do Aplicativo;
* Criado Modais com as informações sobre o aplicativo.

## Observações
![passo1](https://user-images.githubusercontent.com/35435199/89967652-6b95bf80-dc28-11ea-8b91-cda3f3a9ab15.gif)
![passo2](https://user-images.githubusercontent.com/35435199/89967493-f6c28580-dc27-11ea-8144-1e964ed4fbc4.gif)

2020-08-12 14:42 UTC, Phe0 commented
@devsalula @juniopereirab @dudamelo82 
As imagens estão com resolução ruim no meu celular, tentem trocar de png pra svg pls

2020-08-12 17:23 UTC, devsalula commented
@Phe0 fiz as correções, confere novamente. Instalei a react-native-svg, dê um yarn install antes de buildar.

2020-08-12 22:10 UTC, Phe0 requested changes

2020-08-12 22:10 UTC, Phe0 commented on app/src/pages/InformationsCenter/index.js
> +                <Text style={styles.headerText}> Central de Informações </Text>
Adicionem o header das páginas pelo react navigation em vez de fazer uma view com texto para manter o padrão pls

2020-08-13 21:03 UTC, Phe0 commented
@devsalula @dudamelo82 tem correção pra fazer rs

2020-08-14 01:42 UTC, devsalula commented
@Phe0 arrumei rs.
Eu tbm tive que remover a lib que estava usando pra renderizar o SVG pq estava deprecada, utilizei outra pra resolver esse problema.

2020-08-17 20:54 UTC, Phe0 approved these changes

2020-08-17 20:54 UTC, merged