Introslide m19
P-Name-Undefined/Frontend pull request #117
Opened 2020-08-25 22:27 UTC by PedroLimass

## Descrição 

Criação do Slide introdutório ainda é necessário configurar os assets entre outros. Mas o principal é testar o asyncStorage que a principio está funcionando  na minha maquina. A branch relacionado a esse tópico seria a introslideM19.

P.S: Realmente é apenas para testar esse PR. Não efetuem o merge o código ainda precisa de pequenos ajustes código ta feio mesmo.

## Resolve (Issues)

Issues que foram resolvidas com o PR

## PRs relacionados, se houver

branch | PR
------ | ------
outro_pr_relacionado | [link]()

## Tarefas gerais realizadas
* Tarefa 1
* Tarefa 2

2020-08-26 01:04 UTC, DanilloGS requested changes
Crie uma pasta somente para essas imagens com o nome de "TutorialImages" ou algo do tipo e mude o local dela para dentro do images do assets

2020-08-26 01:04 UTC, DanilloGS commented on app/src/pages/FirstAccessTutorial/index.js
> +    const value = await AsyncStorage.getItem('hasOnborded');
Para usar o AsyncStorage, a string deve ser idêntica a da linha acima, pois da forma que está implementado sempre terá um retorno NULL

2020-08-26 01:04 UTC, DanilloGS commented on app/src/pages/FirstAccessTutorial/index.js
> +    const value = await AsyncStorage.getItem('hasOnborded');
Sugiro que mude o nome *value*, para *neverShowAgain* e a string *hasOnborded:value* para *userFirstAccess* ou algo do tipo

2020-08-26 01:04 UTC, DanilloGS commented on app/src/pages/FirstAccessTutorial/index.js
> +export default IntroSlide;
O nome do arquivo deve ter o mesmo nome da componente que está sendo exportada, assim evita equívocos durante futuras manutenções. Troque o nome do arquivo *FirstAccessTutorial* para *IntroSlide* ou vice-versa.

2020-08-26 01:04 UTC, DanilloGS commented on app/src/pages/FirstAccessTutorial/index.js
> +const IntroSlide = () => (
Para que o código siga um padrão de desenvolvimento, é preferível, que se utilize:
```
export default function IntroSlide() {
     const functionNum1 = () => {<Your Code Here>}
     const functionNum2 = async () => {<Your Code Here>}
     const functionNum3 = () => (<Your Code Here>)
     return(
          <Your Code Here>
     );
};
```

2020-08-26 01:04 UTC, DanilloGS commented on app/src/pages/FirstAccessTutorial/index.js
> +        containerViewStyle={{
Passe o CSS para um arquivo de *styles.js*, para evitar repetição de código e deixar a pagina mais limpa. Para os CSS que possuem o HEX da cor e a família da fonte, é disponibilizado dentro da pasta de assets tanto a fonte quanto as cores padrões do projeto, só é necessário importá-las.

2020-08-26 01:04 UTC, DanilloGS commented on app/src/Navigation/index.js
> +    const isFinishedIntroSlide = async () => {
Para que a função tenha o resultado esperado, ela deve se encontrar dentro de um useEffect(). Da forma como a função está sendo implementada ela nunca será chamada, e se for chamada, de alguma forma, será depois que o react renderizou a página, podendo causar um problema de Memory Leak.

2020-08-26 01:04 UTC, DanilloGS commented on app/src/Navigation/index.js
> +        const value = await AsyncStorage.getItem('hasOnborded');
Troque o nome da variável para um nome mais intuitivo

2020-08-26 01:08 UTC, DanilloGS commented
Não esqueça de fazer um pull da develop para sua branch antes de submeter o PR novamente.

2020-09-11 22:21 UTC, juniopereirab approved these changes
Por mim funcionou de boas...

2020-09-11 22:27 UTC, merged