Hotfix tela de minhas ajudas
P-Name-Undefined/Frontend pull request #140
Opened 2021-05-05 22:27 UTC by devsalula

## Descrição 

Correção do bug na tela de minhas ajudas

2021-05-10 21:52 UTC, RcleydsonR reviewed
Certinho, foi resolvida a questão do bug dos cards de ajuda quando clicava para ver minhas ajudas, porém, mesmo com a visualização dos cards, o botão de delete não está funcionando !

2021-05-10 21:59 UTC, RcleydsonR approved these changes
Mas como a proposta desse PR é justamente arrumar o bug de aparecer a tela de ajuda então está corretíssimo, bom trabalho !

2021-05-10 22:00 UTC, mangabeiras approved these changes, later dismissed
Muito bom! Testei com a devel do back e funcionou. Entretando, ocorreu um erro ao tentar excluir meus pedidos. Como a proposta do pr era corrigir o problema da tela, julgo que foi corrigida

2021-05-10 22:46 UTC, mangabeiras requested changes
Muito bom, entretando achei um erro

2021-05-10 22:46 UTC, mangabeiras commented on app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.js
> +    const help = route.params.helpOffer;
A alteração dessa linha provocou bug ao tentar verificar os detalhes de uma oferta. A maneira:
'const { help } = route.params;' permite o funcionamento correto sem bug

2021-05-10 22:52 UTC, mangabeiras commented on app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.js
> +    const help = route.params.helpOffer;
Para reproduzir o erro:
- Faça uma oferta,;
- Se candidate para ela em outra conta;
- Vá em /Atividades/Interações e clique na interação

2021-05-21 21:46 UTC, devsalula commented
@mangabeiras corrigido!

2021-05-26 21:50 UTC, devsalula commented
@mangabeiras não esquece de mim, rs

2021-05-26 22:19 UTC, mangabeiras approved these changes
Aee, agora tudo funcionou perfeitamente. Muito bom, jamais esqueceria kkk!

2021-05-26 22:19 UTC, merged