Bug das notificações de oferta de ajuda
P-Name-Undefined/Frontend pull request #158
Opened 2021-06-23 23:32 UTC by Phe0

## Descrição 

Esse PR passa a responsabilidade de get do oferta de ajuda da página de notificações para a própria página de oferta.
Isso resolve o problema das notificações 

## Resolve (Issues)

[171](https://github.com/mia-ajuda/Documentation/issues/171)

## PRs relacionados, se houver

branch | PR
------ | ------
Bugfix-offerNotification | [link](https://github.com/mia-ajuda/Backend/pull/106)

## Tarefas gerais realizadas
* Passando a responsabilidade de pegar os dados de uma oferta para a própria página de oferta

2021-07-02 20:45 UTC, RcleydsonR approved these changes
Testando junto ao backend parece estar correto, a notificação está levando a oferta de ajuda ! Bom trabalho pessoal !

2021-07-07 00:37 UTC, RcleydsonR requested changes
Então @Phe0, parece que com as alterações quebrou a parte de 'interações' do app, quando clica em qualquer interação que seja ele retorna uma msg de erro !


https://user-images.githubusercontent.com/74625814/124682899-4ba36600-dea2-11eb-92d7-5897d0fb1f54.mp4

2021-07-08 21:08 UTC, RcleydsonR approved these changes
Perfeito galera, foi acordado em comum consenso de que a questão das interações seria referente a outra issue de bug, esta cumpre seu papel !

2021-07-09 20:13 UTC, RcleydsonR commented
Percebi que o bug que causava tela vermelha nas interações era na mudança dos paramêtros passado pra tela myOfferHelpDescription.
1. A mudança era pra passar somente o helpId e na tela de history passava todo o help (objeto)
2. As requisições (get) das telas de ofertas eram pra rota: "HelpOffer", já a da interação (history) era pra rota: "Help"

Logo alterei a maneira de enviar os parâmetros, agora enviando também a rora (Help ou HelpOffer) e também passei a enviar o helpId nas interações (history)

2021-07-12 22:46 UTC, juniopereirab reviewed
A funcionalidade está correta, Porém vai ser aberto uma nova issue (para a próxima Release / Refatoração / Versão ), referente à versão do Expo.

2021-07-12 22:46 UTC, merged