Fix the campaign message
P-Name-Undefined/Frontend pull request #162
Opened 2021-07-27 23:42 UTC by DaviMarinho

Co-authored-by: Ithalo Azevedo <ithaloazevedoo@gmail.com>
Signed-off-by: DaviMarinho <davii_marinho@hotmail.com>

## Descrição 

Corrigida a mensagem da campanha.

## Resolve (Issues)

#187 (https://github.com/mia-ajuda/Documentation/issues/187)

## Tarefas gerais realizadas
- [x] Corrigir mensagem na modal.

2021-07-29 15:07 UTC, RcleydsonR requested changes
Mudança na mensagem de oferta de ajuda.

2021-07-29 15:07 UTC, RcleydsonR commented on app/src/pages/HelpPages/CreateHelpOffer/index.js
> +                message="Sua solicitação de ajuda foi criada com sucesso!"
Excelente trabalho, porém essa mensagem está errada, como se trata da criação de uma oferta de ajuda, uma mensagem melhor seria: "Sua oferta de ajuda foi criada com sucesso!"

2021-07-30 15:23 UTC, DaviMarinho commented on app/src/pages/HelpPages/CreateHelpOffer/index.js
> +                message="Sua solicitação de ajuda foi criada com sucesso!"
É verdade, não me atentei a esse detalhe. Já está arrumado!

2021-07-30 16:12 UTC, RcleydsonR approved these changes
Agora está tudo perfeito, show de bola !

2021-07-30 16:53 UTC, merged