[WIP] US44 - Listagem de pessoas interessadas
P-Name-Undefined/Frontend pull request #164
Opened 2021-07-29 18:13 UTC by RcleydsonR

## Descrição 

PR em progresso, será realizada a listagem de pessoas interessadas em ofertas de ajuda de acordo com a issue [#124](https://github.com/mia-ajuda/Documentation/issues/124), provavelmente componentizando a funcionalidade já existente de listagem de pessoas interessadas em pedidos de ajuda.

## Resolve (Issues)

[#124](https://github.com/mia-ajuda/Documentation/issues/124)

## Tarefas gerais realizadas
* Em progresso

2021-08-06 21:23 UTC, RcleydsonR commented
@DLBrianPina Pode fazer o review ?

2021-08-11 22:36 UTC, devsalula requested changes
Galera parabéns pelo trabalho. Entretanto encontrei alguns probleminhas.

1º - Na tela de **oferta de ajuda**, ao exibir o botão para listar possíveis **ajudados** ele está exibindo a descrição no botão de "possíveis ajudantes". Sugestão: Troque o título do botão para "Interessados na Ajuda". Segue o print onde estou solicitando a alteração:
![Group 27](https://user-images.githubusercontent.com/35435199/129111545-d0488851-f08a-4c27-a99c-28d786d606c3.png)

2º - O botão para clicar nas pessoas interessadas na ajuda não está funcionando. Ao clicar o comportamento esperado era que abrisse uma modal de confirmação do interessado. Entretanto ao clicar no botão nada acontece.

Dando uma rápida olhada no código, eu percebi que esses dois problemas estão acontecendo porque o componente de Interessados na Ajuda (`ListPossibleInteresteds`) está sendo compartilhado tanto entre quem abre uma ajuda quanto para quem abre uma oferta de ajuda. Só que a implementação do componente só está levando em consideração quem abre um pedido de ajuda.
Exemplo nesse método aqui:
```
        const renderClickAction = (interestedId) => {
            if (routeId == 'Help') {
                {
                    setSelectedInterestedId(interestedId);
                    setConfirmationModalVisible(true);
                }
            }
        };
```
Minha sugestão é tentar aumentar o nível de abstração desse componente `ListPossibleInteresteds`. Tente criar um componente mais abstrato com os métodos que tanto os possíveis ajudante, quanto os possíveis interessados na ajuda possam compartilhar. Uma forma de se fazer isso é utilizando um padrão de projeto chamado [Factory Pattern](https://refactoring.guru/pt-br/design-patterns/factory-method).
Exemplo de [Factory Pattern em React Native](https://gist.github.com/Zacaria/39ff1278fe423b22bd3b25f0f1ebc6ce).

2021-08-12 23:37 UTC, RcleydsonR commented
Olá @devsalula, muito obrigado pelo feedback, então, comentando um pouco sobre o 2º ponto problema que você encontrou

- Não faz parte dessa issue possuir uma ação ao clicar no Possível Necessitado, por isso está a presença do if, porque essa implementação será na próxima issue e ela viria para substituir aquele if ressaltado !
- Curti muito esse padrão de projeto que você trouxe, percebi que tem algumas dificuldades de implementar em js devido a linguagem não suportar classe abstrata e nem interfaces (diferentemente do ts). Conversando com o João, ele também levantou um padrão de projeto que seria interessante para resolver a questão da próxima issue que seria o [Strategy pattern](https://refactoring.guru/pt-br/design-patterns/strategy), tendo em vista esses 2 possíveis padrões, vou discutir com o pessoal da issue [125](https://github.com/mia-ajuda/Documentation/issues/125) para decidir qual o melhor para aplicar, pode ser ?.

Agradeço imensamente o feedback, já corrigi o primeiro problema, e esse segundo peço pra deixar pra consertar na issue que convém que é a que já estou trabalhando sobre ! Justamente para não atrasar muito esse PR.

2021-08-18 22:38 UTC, devsalula approved these changes

2021-08-18 22:38 UTC, merged