US45 - Aceitação de pessoas interessadas para ajudar
P-Name-Undefined/Frontend pull request #168
Opened 2021-08-23 22:34 UTC by RcleydsonR

## Descrição 

Foi implementado no front-end a possibilidade de escolher um ou mais ajudados para sua oferta de ajuda, bem como o dono visualizar as informações das pessoas que foram selecionadas.

## Resolve (Issues)

#125 

## PRs relacionados, se houver

branch | PR
------ | ------
US45 - Aceitação de pessoas interessadas para ajudar | [mia-ajuda/backend](https://github.com/mia-ajuda/Backend/pull/116)

## Tarefas gerais realizadas
* Acrescentado botão de "Ajudados escolhidos" na tela de minhas ofertas de ajuda.
* Possibilidade de aceitar um ou mais ajudados na oferta.

2021-09-15 22:46 UTC, thiagohdaqw requested changes
Bom trabalho, galera! Encontrei alguns probleminhas que listo abaixo:

### 1. Dá erro quando clico no botão de interessados:
<img src="https://user-images.githubusercontent.com/54081877/133518939-28df2e1b-5287-4a2c-9ba1-ad314b7e0763.jpg" width="250" />
<img src="https://user-images.githubusercontent.com/54081877/133519032-e8b53532-a1db-4b04-b726-af1071fcb232.jpg" width="250" />

### 2. Aqui deveria ser `Aguarde o dono da `**oferta**` entrar em contato.`, não?
<img src="https://user-images.githubusercontent.com/54081877/133519590-cb8fd95b-2522-4fa7-b0d6-182718568600.jpg" width="250" />

2021-09-15 22:49 UTC, thiagohdaqw commented
Eu, como um usuário sendo ajudado, senti falta da oferta na pagina de interação, pois só a encontrei na pagina de notificação e 
 não lembro de ter algo destacando. Isso deveria ser tratado nessa US?

2021-09-17 03:19 UTC, RcleydsonR commented
@thiagohdaqw , agradeço novamente o feedback, como discutido em daily, a parte das interações se torna mais interessante de ser implementada em outra user story ! Então para esse PR em específico não há necessidade de avaliação, visto que o trabalho incremental visa dar incrementos constantes ao projeto, não é interessante acoplar quase uma feature inteira em apenas uma issue.

Repeti a mensagem do back-end em virtude de terem 2 iguais, acho interessante quando tiver esse tipo de discussão, ser feita ou na própria issue (dentro da documentação), ou em algum PR específico.
Att. Rafael Ramos.

2021-09-17 03:20 UTC, RcleydsonR commented
Agora, creio eu que está tudo correto, aguardo um retorno !
Retirei também os code smells que você tinha me alertado em particular.

2021-09-17 22:53 UTC, thiagohdaqw approved these changes
Parabéns a equipe, trabalho está muito bem feito! Pelo que testeia qui, ta tudo bem funcional e dentro do esperado da issue, muito bom mesmo. 
## So peço para quando for merjar, merjar junto com o backend.

2021-09-20 17:41 UTC, merged