Criação de novo marcador e atualização do card de atividades
P-Name-Undefined/Frontend pull request #232
Opened 2023-05-07 14:26 UTC by sudjoao

## Descrição 
Criação de novo marcador e atualização do card de atividades.

## Resolve (Issues)
[US12 - Eu, como usuário, desejo visualizar as informações de pedidos e ofertas de forma clara a fim de entender do que se trata](https://github.com/mia-ajuda/Documentation/issues/232)

## PRs relacionados, se houver

branch | PR
------ | ------
outro_pr_relacionado | [link]()

## Tarefas gerais realizadas
* Criação de novo marcador para o mapa;
* Criação de lógica de marcador de novo pedido;
* Criação de utils para calculo de dia e padronização dos ícones de oferta, pedido e campanha.

2023-05-14 03:46 UTC, guibrbs requested changes

2023-05-14 03:46 UTC, guibrbs commented on app/src/components/molecules/ActivityMarker/index.jsx
> +        >
Tentei rodar localmente e não deu certo

<img src="https://github.com/mia-ajuda/Frontend/assets/88190414/67ba31e4-72f5-4a91-9b9b-88ab8509306d" width="200"/>

Fiz o console log na key `latitude` dentro da chave `coordinates` e retornou isso:

![image](https://github.com/mia-ajuda/Frontend/assets/88190414/7db0bd36-0afe-4b94-a53d-18f57d7a3afc)

Tentei criar um usuário novo e também não funcionou, se tiver alguma configuração a mais pra fazer funcionar da a call

E sim, rodei nas branchs certas atualizadas :laughing: 

![image](https://github.com/mia-ajuda/Frontend/assets/88190414/3cc04d46-2ad5-458d-a953-9a0baa7dbc43)

2023-05-14 12:35 UTC, sudjoao commented on app/src/components/molecules/ActivityMarker/index.jsx
> +        >
Era uma soma que eu tinha adicionado ai só pros pontos não se sobreporem, corrigido

2023-05-17 05:07 UTC, guibrbs requested changes
Vou deixar pra mudança mas se não fizer sentido o que eu apontei aí só me falar que eu aceito

2023-05-17 05:07 UTC, guibrbs commented on app/src/pages/Main/index.js
> +            );
Localmente tive 3 campanhas que retornaram undefined, não sei o motivo

![image](https://github.com/mia-ajuda/Frontend/assets/88190414/1ac2398b-beee-40de-8491-5b1fa778d0c9)

O que ocasionou o erro:

![image](https://github.com/mia-ajuda/Frontend/assets/88190414/cfd4e10c-c370-40ef-b69c-25005e1d1b0d)

Se quiser certificar se tem alguma possibilidade de estar retornando undefined...

2023-05-17 05:07 UTC, guibrbs commented on app/src/components/molecules/ActivityMarker/index.jsx
> +            <View className="bg-white py-1 px-2 w-32 rounded-full rounded-bl-none shadow-sm shadow-black flex-row items-center justify-center">
[SUGESTÃO]

Pelo menos no meu emulador de centavos ficou um pouco difícil de ver esses marcadores quando está sobre uma parte com predominância branca. Talvez dar uma estilização de elevated do material ficaria show

<img src="https://github.com/mia-ajuda/Frontend/assets/88190414/6e68de5c-77a4-4cb5-ae75-fdac1b4fd3d9" width="250" />

2023-05-17 12:59 UTC, sudjoao commented on app/src/pages/Main/index.js
> +            );
Fala meu bom, isso tá ocorrendo devido a uma inconsistência que tinha no arquivo de seed do backend, tanto que você vai observar que eu alterei o arquivo de seeds agora, onde ele esta populando as atividades com localização, pra vc atualizar seu banco de dados, basta comentar as linhas do seed que verificam se tem alguma atividade criada e subir o servidor, que ele vai recriar toda essa parte, se precisar de ajuda nessa parte só avisar.

2023-05-18 01:07 UTC, guibrbs requested changes
Como adicionamos a localização para aparecer nas ofertas, quando eu abro o mapa dessa tela e clico na oferta que eu criei, é redirecionado para a tela em que é possível se candidatar. Precisamos privar o usuário dono da oferta de navegar para essa tela e possivelmente indicar com "sua oferta" ou "seu pedido"

2023-05-18 01:23 UTC, guibrbs approved these changes
:godmode:

2023-05-18 01:30 UTC, merged