Refatora a tela de "Meus Pedidos"
P-Name-Undefined/Frontend pull request #233
Opened 2023-05-13 02:34 UTC by guibrbs

## Descrição 

Descrição concisa do que foi feito

## Resolve (Issues)

Issues que foram resolvidas com o PR

## PRs relacionados, se houver

branch | PR
------ | ------
outro_pr_relacionado | [link]()

## Tarefas gerais realizadas
* Tarefa 1
* Tarefa 2

2023-05-14 04:40 UTC, guibrbs commented
https://github.com/mia-ajuda/Frontend/blob/625d29367796255a850bd7a5a4488fc3a4b3bd90/app/src/pages/ActivitiesPages/MyOfferedHelp/MyOfferHelpDescription/index.jsx#L70-L71

```js
const possibleHelpedUsersBadgeValue = (help.possibleHelpers?.length || 0) + (help.possibleEntities?.length || 0);
```

2023-05-14 12:24 UTC, sudjoao requested changes
Bom trabalho, só algumas mudanças e comentários pra você avaliar

2023-05-14 12:24 UTC, sudjoao commented on app/src/components/atoms/DefaultButton/index.jsx
> +                className={`text-center text-light font-ms-semibold text-lg ${textStyle}`}
Como a ideia dos botões é ser padronizado em todas as telas, será que faz sentido a gente começar a mudar o text style deles? Será que a gente não pode trabalhar com a ideia de variante aqui não? Que aí se algum outro lugar quiser utilizar um botão do mesmo estilo só precisa passa ro variantezinhas ao invés de um textStyle.

2023-05-14 12:24 UTC, sudjoao commented on app/src/components/atoms/UserCard/index.jsx
> +        }
Só um comentário mesmo, porque era algo que tínhamos discutido na sexta, será que isso aqui não pode ser movido pro context e chamado diretamente de lá? (Talvez possamos fazer isso depois em uma issue a parte)

2023-05-14 12:24 UTC, sudjoao commented on app/src/components/atoms/DefaultButton/index.jsx
> +            android_ripple={{ color: '#D2D2D2' }}
Como estamos utilizando muito essa cor, e se um dia quisermos mudar, talvez valha a pena adiciona-la a nossa paleta do tailwind e usar ela diretamente de lá.

2023-05-14 12:24 UTC, sudjoao commented on app/src/components/atoms/UserCard/index.jsx
> +            android_ripple={{ color: '#D2D2D2' }}
Mesma coisa sobre a cor aqui.

2023-05-14 12:24 UTC, sudjoao commented on app/src/components/atoms/UserCard/index.jsx
> +    const [updateData, setUpdateData] = useState(true);
É realmente necessário esse State aqui? Pq ele começa como true, depois vai pra false e n muda nunca mais de estado, e ele só é utilizado no useEffect.

2023-05-14 12:24 UTC, sudjoao commented on app/src/components/atoms/UserCard/index.jsx
> +    const [user, setUser] = useState();
Só deixando a reflexão aqui, será que faz sentido a gente ter a lógica de chamada de API para puxar os dados de um usuário dentro de um átomo? Será que não seria melhor a página pai já passar os dados do usuário diretamente pra ele?

2023-05-16 04:00 UTC, guibrbs commented on app/src/components/atoms/UserCard/index.jsx
> +    const [user, setUser] = useState();
Feito

2023-05-16 04:00 UTC, guibrbs commented on app/src/components/atoms/UserCard/index.jsx
> +    const [updateData, setUpdateData] = useState(true);
Feito

2023-05-16 04:01 UTC, guibrbs commented on app/src/components/atoms/DefaultButton/index.jsx
> +            android_ripple={{ color: '#D2D2D2' }}
Criei a cor pro tailwind, mas não consegui achar meios de aproveitar o tailwind e adicionar em props de styles...

2023-05-16 04:01 UTC, guibrbs commented on app/src/components/atoms/UserCard/index.jsx
> +        }
Feito

2023-05-16 04:01 UTC, guibrbs commented on app/src/components/atoms/DefaultButton/index.jsx
> +                className={`text-center text-light font-ms-semibold text-lg ${textStyle}`}
Feito

2023-05-16 04:05 UTC, guibrbs commented
### Alterações que serão finalizadas nesse PR

- Notificações bugando na hora de navegar para as novas telas de pedido e oferta;
- Cards do perfil na seção `Atividades` navegando para rotas indevidas

2023-05-16 10:18 UTC, sudjoao commented on app/src/components/atoms/DefaultButton/index.jsx
> +            android_ripple={{ color: '#D2D2D2' }}
Você consegue importar o arquivo tailwind.config.js como um objeto e utilizar todos os valores dele como por exemplo:
`tailwindConfig.theme.extend.colors.primary`

Tem algo parecido no arquivo`Frontend/app/src/components/organisms/ActivityCard/index.jsx`

2023-05-18 00:05 UTC, sudjoao requested changes
Opa, tá ficando show demais, acho que dá pra fazer algumas alterações no informative text, pra se tornar um componente mais geral para toda a aplicação, fora isso, deixei só uns comentários que não são tão essenciais assim.

2023-05-18 00:05 UTC, sudjoao commented on app/src/components/atoms/InformativeField/index.jsx
> +    };
Acho que esses 2 casos são muito específicos para serem um variant, a ideia principal de variantezinhas é padronizar algo que será utilizado em diversas telas, e talvez não seja o caso disso aqui, acho que o text pode vir como prop aqui.

2023-05-18 00:05 UTC, sudjoao commented on app/src/components/atoms/InformativeField/index.jsx
> +        },
Opa, só uma reflexão aqui, será que é legal manter o title e o text nesses casos com essa string padrão? Talvez não seria melhor pega-los como prop? (Assim como está na variant informative). Ou até mesmo nem guarda-los no variant, só passar o title e text, que vem como prop, dentro do componente de Texto, pq isso tornaria esse componente mais adaptável para qualquer caso, onde as variantes só guardariam o style.

2023-05-18 00:05 UTC, sudjoao commented on app/src/components/atoms/UserProfileCard/index.jsx
> +    const { userId, photo, phone, name, email } = props;
Só uma dúvida mesmo, teve algum motivo aqui pra passar a props como parâmetro e desestruturar ela só depois? Isso aqui não afeta as sugestões de props que o código faz não?

2023-05-18 00:05 UTC, sudjoao commented on app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
> +    }, [updateData]);
Aqui não da pra utilizar um useFocusEffect? Ou será que ele não reconhece fechar modal como um evento de foco na tela? Talvez valha o teste pra não ficar tendo que usar o updateData.

2023-05-18 00:05 UTC, sudjoao commented on app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
> +                />
Dando continuidade sobre a questão do comentário no arquivo UserProfileCard, as vezes passando o helper todo como prop, a verificação de se a prop(helper) existe faça mais sentido.

2023-05-18 00:05 UTC, sudjoao commented on app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
> +    const ownerPhoto = (help && help.user && help.user.photo) || user.photo;
```suggestion
    const ownerPhoto = (help?.user?.photo) || user.photo;
```

2023-05-18 01:55 UTC, guibrbs commented on app/src/components/atoms/UserProfileCard/index.jsx
> +    const { userId, photo, phone, name, email } = props;
Faz sentido, afeta sim. Queria passar somente as props essenciais ao invés de um objeto grande pra otimizar o uso, mas alterei a lógica toda pra passar mesmo as infos do user, ficou mais legível

2023-05-18 01:58 UTC, guibrbs commented on app/src/components/atoms/InformativeField/index.jsx
> +    };
Feito

2023-05-18 02:01 UTC, guibrbs commented on app/src/components/atoms/InformativeField/index.jsx
> +        },
Faz sentido o título e o texto serem passados em cada chamada do componente sim, fica mais adaptável mesmo. Corrigido

2023-05-18 04:45 UTC, guibrbs commented on app/src/pages/ActivitiesPages/MyRequestedHelp/MyRequestHelpDescription/index.jsx
> +    }, [updateData]);
Tentei aplicar, no caso tive que manter o updateData pq ele é passado para o ExpandedModal, mas acho que da pra refatorar dentro desse componente porém não nesse PR

2023-05-18 15:44 UTC, sudjoao approved these changes
Parabéns pelo trabalho, tanto o código quanto o layout tão excepcionais 🔥

2023-05-19 00:46 UTC, merged