Refatoração da página principal
P-Name-Undefined/Frontend pull request #244
Opened 2023-06-10 23:44 UTC by guibrbs

## Descrição 

Descrição concisa do que foi feito

## Resolve (Issues)

Issues que foram resolvidas com o PR

## PRs relacionados, se houver

branch | PR
------ | ------
outro_pr_relacionado | [link]()

## Tarefas gerais realizadas
* Tarefa 1
* Tarefa 2

2023-07-02 19:46 UTC, sudjoao requested changes
Algumas dúvidas e mudanças.

2023-07-02 19:46 UTC, sudjoao commented on app/colors.js
> -        900: 'rgba(53,53,53,0.9)',
Teve algum motivo especifico para apagar essas cores? Acho que elas são usadas em alguns lugares da aplicação, não?

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/atoms/Chips/index.jsx
> +        isSelected || selected ? 'bg-secondary-500 border-0' : 'bg-white';
Será que aqui não faz sentido iniciar o isSelected com o valor do selected? Para gente não ter que fazer essa dupla verificação desses 2 campos.
```suggestion
    const [isSelected, setIsSelected] = useState(selected);
    const chipColor =
        selected ? 'bg-secondary-500 border-0' : 'bg-white';
```

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/atoms/DefaultButton/index.jsx
> +        );
Opa, dúvida aqui, a ideia é que os botões com ícone não possam ter o comportamento de loading?

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/EntityActivity.jsx
> +                </View>
Opa, talvez eu tenha entendido errado, mas agora o botão tem a prop width, certo? Por que aqui temos que criar uma view com width ao invés de só passar a prop width?

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +);
Talvez a gente possa transformar isso em um componente depois para utilizar em outras ocasiões.

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +        const activities = inputedActivities.length ? inputedActivities : null;
Não tem problema passar um array vazio pro back, então da pra remover essa validação aqui.

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +            })();
A forma como esse código foi escrito está um pouco fora do comum, será que não vale mais a pena fazer algo como:
```suggestion
            const updateActivities = async () => {
                await updateActivitiesList();
                bottomSheetRef.current.dismiss();
            });
            updateActivities();
```

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +                            key={activity._id + activityArray}
Opa, será que aqui é necessário passar todo um array como key? Será que não podemos apenas utilizar o id + o type?
```suggestion
                            key={activity._id + type}
```

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +                onPress={() => filterButtonAction()}
```suggestion
                onPress={filterButtonAction}
```

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/molecules/ActivityMarker/index.jsx
> +    const isFocused = focused ? markerColor : 'bg-white';
Opa, alteração só pra deixar as variáveis mais descritivas
```suggestion
    const markerDefaultColor = isRiskGroup ? 'bg-danger-darker' : 'bg-primary-darker';
    const currentMarkerColor = focused ? markerDefaultColor : 'bg-white';
```

2023-07-02 19:46 UTC, sudjoao commented on app/src/components/molecules/FloatingIconButton/index.jsx
> +    const positionY = customTop ? customTop : 'top-2';
Incorporando meu amigo Gabriel Davi, é possível fazer isso sem ternário.
```suggestion
    const positionY = customTop || 'top-2';
```

2023-07-02 19:46 UTC, sudjoao commented on app/src/pages/Main/index.jsx
> +        createInteraction(user, navigation, creationPage);
Será que não vale a pena passa o creationpage como parâmetro direto?

2023-07-04 18:06 UTC, guibrbs commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +        const activities = inputedActivities.length ? inputedActivities : null;
Mas não tem como fazer split em array, como é feito na controller (enviando print pq não tem como enviar código de outro repositorio):

![image](https://github.com/mia-ajuda/Frontend/assets/88190414/b4f70dfc-333f-4aaa-9153-af90c4a74151)

2023-07-04 18:09 UTC, guibrbs commented on app/src/components/molecules/FloatingIconButton/index.jsx
> +    const positionY = customTop ? customTop : 'top-2';
feito

2023-07-04 18:09 UTC, guibrbs commented on app/src/components/molecules/ActivityMarker/index.jsx
> +    const isFocused = focused ? markerColor : 'bg-white';
feito

2023-07-04 18:09 UTC, guibrbs commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +                onPress={() => filterButtonAction()}
feito

2023-07-04 18:10 UTC, guibrbs commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +                            key={activity._id + activityArray}
feito

2023-07-04 18:10 UTC, guibrbs commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +            })();
feito

2023-07-04 18:10 UTC, guibrbs commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +);
feito, transformei em átomo

2023-07-04 18:11 UTC, guibrbs commented on app/src/components/modals/ActivityBottomSheet/EntityActivity.jsx
> +                </View>
Só tinha esquecido de tirar dai, arrumei

2023-07-04 18:12 UTC, guibrbs commented on app/src/components/atoms/DefaultButton/index.jsx
> +        );
arrumei a lógica, é pro loading aparecer e o resto não

2023-07-04 18:12 UTC, guibrbs commented on app/src/components/atoms/Chips/index.jsx
> +        isSelected || selected ? 'bg-secondary-500 border-0' : 'bg-white';
feito

2023-07-04 18:12 UTC, guibrbs commented on app/colors.js
> -        900: 'rgba(53,53,53,0.9)',
maldito dev jr

2023-07-04 23:52 UTC, guibrbs commented on app/src/pages/Main/index.jsx
> +        createInteraction(user, navigation, creationPage);
feito

2023-07-05 00:38 UTC, sudjoao commented on app/src/components/modals/ActivityBottomSheet/FilterActivity.jsx
> +        const activities = inputedActivities.length ? inputedActivities : null;
Opa, só entrando mais a fundo nessa, quando você passa algo como query param, ele sempre vai chegar como string pro back, então no caso, um array vazio nada mais seria que uma string nessa linha de código, mas como você tem a opção getAll ao invés de um array vazio para buscar os dados do back talvez fosse necessário apenas remover esse ||, mas fica a seu critério.

2023-07-05 00:38 UTC, sudjoao approved these changes
🚀 mandou bem demais

2023-07-05 00:58 UTC, merged