Us17 Escolher ajudante & US26 - Concluir ajuda pelo ajudado
P-Name-Undefined/Frontend pull request #28
Opened 2020-05-04 21:42 UTC by joberthrogers18

## Descrição 
Foi criada a componente de listagem de possíveis ajudantes, além de criar o botão para o  finalizar a ajuda por parte do ajudado.

## Resolve (Issues)
[US17](https://github.com/mia-ajuda/Documentation/issues/20)
[US26](https://github.com/mia-ajuda/Documentation/issues/30)

## Tarefas gerais realizadas
- Criado componente de listagem de possíveis ajudantes na descrição das helps quando for da parte do ajudado.
- Foi adicionado um botão de finalizar ajuda à tela de ofertas em andamento por parte do ajudado.

# Como testar
- Logue no aplicativo.
- Crie uma ajuda com seu usuário logado.
- Vá em aba de minhas ajudas (segunda aba da esquerda para direita).
- Verifique se sua ajuda esta listada.
- Abra o Postman ou Insomnia.
- Coloque a requisição localhost:8000/api/help/possibleHelper/:idHelp/:idHelper.
- Substitua idHelp pelo id da Ajuda que você criou e idHelper pelo id de um usuário qualquer que não seja o seu.
- Realize a requisição.
- Observe se a ajuda escolhida tem uma badge indicando que tem possíveis usuários (canto superior direito do card da ajuda).
- Entre na descrição da ajuda.
- Aperte no botão abaixo "Possíveis Ajudantes".
- Uma lista de possíveis ajudantes será mostrada.
- Clique em qualquer um dos ajudantes.
- A página de descrição será mudada para um card com o voluntário escolhido.
- Depois Aperte finalizar para encerrar a ajuda por parte do ajudado.

2020-05-04 22:55 UTC, GabrielDVpereira requested changes

2020-05-04 22:55 UTC, GabrielDVpereira commented on app/src/components/ListCard/index.js
> +          possibleHelpers,
Ao clicar na lista para dislay, o seguinte erro ocorre

![image](https://user-images.githubusercontent.com/37307099/81020446-33b7f880-8e3f-11ea-9e2a-1ed0e9567654.png)

Falta passar a propriedade possibleHelpers para Helplist opr props

/home/gabriel/Mia Ajuda/Frontend/app/src/components/HelpList/index.js linha 94
![image](https://user-images.githubusercontent.com/37307099/81020542-6d88ff00-8e3f-11ea-879a-10c1bc60b3ae.png)

2020-05-04 23:40 UTC, joberthrogers18 commented on app/src/components/ListCard/index.js
> +          possibleHelpers,
Arrumado, tinha esquecido de verificar isso

2020-05-05 17:21 UTC, GabrielDVpereira commented on app/src/components/ListCard/index.js
> +          possibleHelpers,
Ok! Você conversou com o @darmsDD sobre a navegação da descrição da ajuda no momento de voltar?

2020-05-05 19:42 UTC, darmsDD approved these changes

2020-05-05 19:43 UTC, merged