Avisos de segurancas
P-Name-Undefined/Frontend pull request #76
Opened 2020-07-07 17:36 UTC by DanilloGS

## Título da issue
Avisos de seguranças para o usuário

### Descrição:
Colocar avisos de segurança que lembram o usuários sobre algumas dicas importantes de segurança.
Telas que devem ser colocadas:
- Criar ajuda
   - Aviso: Lembre-se de nunca colocar informações pessoais nos pedidos de ajudas que você cria, pois eles ficam públicos para todo mundo.

- Marcar a localização
   - Aviso: Lembre-se de nunca colocar a posição exata da sua residência, mas sempre em um ponto de referência de fácil acesso. Segurança em primeiro lugar!

- Ofertar ajuda
   - Aviso: Lembre-se que você está lidando com um ser humano. Ao ofertar ajuda, sempre tome cuidado com seus dados pessoais, jamais passe informações sigilosas.

### Critérios de aceitação:

- Foram postos os pop-ups que deem avisos de segurança ao usuário. 
- Foram configurados para que não apareçam todas as vezes que o usuário acessar aquela página. Aqui podem ser feitos dois tipos de configuração:
   - Exibir apenas no primeiro acesso (mais complexo).
   - Colocar um botão "não exibir esse aviso novamente" (mais simples).
- Funcionalidade foi testada.

### Tarefas:

- [x] Colocar pop-ups de aviso
- [x] Configurar corretamente.
- [ ] Testar funcionalidade.

2020-07-07 19:04 UTC, GabrielDVpereira requested changes

2020-07-07 19:04 UTC, GabrielDVpereira commented on app/src/utils/warningPopUp.js
> +    if (dontShowAgainPressed) {
acredito que aqui o certo seria não executar o alert se dontShowAgainPressed retornar um valor, nesse caso, poderia somente dar um "if (dontShowAgainPressed) return " e continuar o código do alert abaixo do if

2020-07-07 19:41 UTC, DanilloGS commented on app/src/utils/warningPopUp.js
> +    if (dontShowAgainPressed) {
@GabrielDVpereira arrumei a condicional que acabou passando desapercebido

2020-07-07 19:42 UTC, DanilloGS commented on app/src/utils/warningPopUp.js
> +    if (dontShowAgainPressed) {
@GabrielDVpereira a partir de agora, todas as vezes que o dado for null ele será, automaticamente, mudado para 'false'

2020-07-08 00:17 UTC, GabrielDVpereira approved these changes

2020-07-08 00:17 UTC, merged