Memory Leak no Login
P-Name-Undefined/Frontend pull request #79
Opened 2020-07-13 22:50 UTC by DanilloGS

## Descrição 
- PR para a correção do vazamento de memória que estava ocorrendo quando o usuário realizava o login na aplicação. Após diversos teste, nenhum outro vazamento fora identificado, com exceção do vazamento na seguinte página.

> Frontend/app/src/pages/authPages/PersonalData

- Que não foi possível a correção. Não foi identificado o local do erro, além de que o vazamento não segue um padrão, o que tornou ainda mais árduo a identificação do mesmo.

- Houve, também, a mudança de
> Firebase.logout()

- Para
>this.signOut()
  
- No seguinte arquivo
> Frontend/app/src/services/User.js

- Após o usuário terminar o fluxo de cadastro, o mesmo, estava sendo redirecionado para dentro do app sem haver a validação prévia do e-mail

## Resolve (Issues)
- Issue de ID 2 na [planilha](https://docs.google.com/spreadsheets/d/14IfnoKbwnVvsfldHnmyZnYVlQdMNqo74cpkLuZtT5L4/edit#gid=0)

## Tarefas gerais realizadas
* Correção do memory leak no login
* Correção no fluxo de cadastro

2020-07-13 23:14 UTC, GabrielDVpereira requested changes

2020-07-13 23:14 UTC, GabrielDVpereira commented on app/src/services/User.js
> +            await this.logOut();
await firebaseService.signOut() por favor utilizar esse logout do firebase

2020-07-14 00:17 UTC, DanilloGS commented
@GabrielDVpereira, o pr agora cumpre todos os requisitos

2020-07-14 13:59 UTC, GabrielDVpereira approved these changes

2020-07-14 14:00 UTC, merged