105 tratamento de erros
P-Name-Undefined/Frontend pull request #90
Opened 2020-07-28 23:00 UTC by darmsDD

## Descrição 

Passar todas as requisições pelo mesmo serviço, neste caso useService. A qual trata todos os erros e chama alertas de erro para todos os erros que possam ocorrer em uma requisição.

## Resolve (Issues)

[105](https://github.com/mia-ajuda/Documentation/issues/105)

## Tarefas gerais realizadas
* Deixa o try catch apenas dentro da useService
* Mostra um alerta de erro para o usuário em qualquer caso de erro com a requisição.

2020-07-28 23:27 UTC, GabrielDVpereira requested changes

2020-07-28 23:27 UTC, GabrielDVpereira commented on app/src/config/envVariables.js
> +console.log(devUrl + 'aa');
console.log de teste, pode deletar

2020-07-28 23:27 UTC, GabrielDVpereira commented on app/src/pages/authPages/PersonalData/index.js
> +        if (!cpfExist.message) {
Esse padrão de user message para verificar o caso de erro não ficou claro, daria pra ter uma solução do tipo cpfExist.error ou algo do tipo

2020-07-29 17:42 UTC, darmsDD commented on app/src/config/envVariables.js
> +console.log(devUrl + 'aa');
removido.

2020-07-29 17:43 UTC, darmsDD commented on app/src/pages/authPages/PersonalData/index.js
> +        if (!cpfExist.message) {
modifiquei pra !cpfExist.error

2020-07-31 19:54 UTC, GabrielDVpereira approved these changes

2020-07-31 19:56 UTC, merged